/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as AboutImport } from "./routes/about";
import { Route as BlogImport } from "./routes/blog";
import { Route as ContactImport } from "./routes/contact";
import { Route as FacilitiesImport } from "./routes/facilities";
import { Route as IndexImport } from "./routes/index";
import { Route as ServicesImport } from "./routes/services";

// Create/Update Routes

const ContactRoute = ContactImport.update({
  id: "/contact",
  path: "/contact",
  getParentRoute: () => rootRoute,
} as unknown);

const BlogRoute = BlogImport.update({
  id: "/blog",
  path: "/blog",
  getParentRoute: () => rootRoute,
} as unknown);

const ServicesRoute = ServicesImport.update({
  id: "/services",
  path: "/services",
  getParentRoute: () => rootRoute,
} as unknown);

const FacilitiesRoute = FacilitiesImport.update({
  id: "/facilities",
  path: "/facilities",
  getParentRoute: () => rootRoute,
} as unknown);

const AboutRoute = AboutImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRoute,
} as unknown);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as unknown);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutImport;
      parentRoute: typeof rootRoute;
    };
    "/facilities": {
      id: "/facilities";
      path: "/facilities";
      fullPath: "/facilities";
      preLoaderRoute: typeof FacilitiesImport;
      parentRoute: typeof rootRoute;
    };
    "/services": {
      id: "/services";
      path: "/services";
      fullPath: "/services";
      preLoaderRoute: typeof ServicesImport;
      parentRoute: typeof rootRoute;
    };
    "/blog": {
      id: "/blog";
      path: "/blog";
      fullPath: "/blog";
      preLoaderRoute: typeof BlogImport;
      parentRoute: typeof rootRoute;
    };
    "/contact": {
      id: "/contact";
      path: "/contact";
      fullPath: "/contact";
      preLoaderRoute: typeof ContactImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/facilities": typeof FacilitiesRoute;
  "/services": typeof ServicesRoute;
  "/blog": typeof BlogRoute;
  "/contact": typeof ContactRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/facilities": typeof FacilitiesRoute;
  "/services": typeof ServicesRoute;
  "/blog": typeof BlogRoute;
  "/contact": typeof ContactRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/facilities": typeof FacilitiesRoute;
  "/services": typeof ServicesRoute;
  "/blog": typeof BlogRoute;
  "/contact": typeof ContactRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/about"
    | "/facilities"
    | "/services"
    | "/blog"
    | "/contact";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/about" | "/facilities" | "/services" | "/blog" | "/contact";
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/facilities"
    | "/services"
    | "/blog"
    | "/contact";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  FacilitiesRoute: typeof FacilitiesRoute;
  ServicesRoute: typeof ServicesRoute;
  BlogRoute: typeof BlogRoute;
  ContactRoute: typeof ContactRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FacilitiesRoute: FacilitiesRoute,
  ServicesRoute: ServicesRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addRouteTypes<FileRouteTypes>();
